version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  backend:
    # build: ../backend
    image: remarkekz/backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/ 
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    # build: ../frontend
    image: remarkekz/frontend:v1.03.2023
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  dbdata:
  static_value:
  media_value: